apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-lists
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-lists
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-lists/overrides.yaml
      - $values/folio-test/common/resources.yaml
      - $values/folio-test/common/sidecar.yaml
      - $values/folio-test/common/probes.yaml
      - $values/folio-test/modules/mod-lists/java_opts.yaml
      - $values/folio-test/modules/mod-lists/extra_env.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 1.1.44
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
