apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-scheduler
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-scheduler
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-scheduler/overrides.yaml
      - $values/common/resources.yaml
      - $values/common/sidecar.yaml
      - $values/common/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 0.0.51
  - ref: values
    repoURL: git@github.com:sul-dlss/folio-eureka.git
    targetRevision: argo-cd
