apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-di-converter-storage
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-di-converter-storage
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-di-converter-storage/overrides.yaml
      - $values/folio-test/modules/mod-di-converter-storage/resources.yaml
      - $values/common/sidecar.yaml
      - $values/common/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 2.2.43
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
