apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: folio-dev
spec:
  project: folio-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: folio-dev
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts/elasticsearch
      chart: elasticsearch
      targetRevision: 19.6.0
      helm:
        valueFiles:
        - $values/folio-dev/infrastructure/elasticsearch.yaml
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: main
      ref: values