apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: folio-dev
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  sources:
    - chart: keycloak
      repoURL: oci://registry-1.docker.io/bitnamicharts/keycloak
      targetRevision: 25.2.20
      helm:
        valueFiles:
          - $values/folio-dev/infrastructure/keycloak.yaml
          - $values/folio-dev/infrastructure/allowed_ips.yaml
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: main
      ref: values
  project: folio-dev
