apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: folio-dev
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  sources:
    - chart: kong
      repoURL: oci://registry-1.docker.io/bitnamicharts/kong
      targetRevision: 12.0.11
      helm:
        valueFiles:
          - $values/folio-dev/infrastructure/kong.yaml
          - $values/folio-dev/infrastructure/allowed_ips.yaml
        skipCrds: true
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: main
      ref: values
  project: folio-dev
