apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail
  namespace: folio-dev
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  sources:
    - chart: mail
      repoURL: https://bokysan.github.io/docker-postfix/
      targetRevision: 4.4.0
      helm:
        valueFiles:
          - $values/folio-dev/infrastructure/postfix.yaml
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: main
      ref: values
  project: folio-dev
