apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-complete
  namespace: folio-dev
spec:
  project: folio-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: folio-dev
  sources:
    - repoURL: https://sul-dlss.github.io/folio-helm-v2/
      targetRevision: 2.23.14
      helm:
        valueFiles:
          - $values/folio-dev/infrastructure/stripes.yaml
          - $values/folio-dev/infrastructure/allowed_ips.yaml
      chart: platform-complete
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: main
      ref: values
operation:
  sync:
    syncStrategy:
      hook: {}