apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-users-keycloak
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-users-keycloak
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-users-keycloak/overrides.yaml
      - $values/folio-test/modules/mod-users-keycloak/resources.yaml
      - $values/folio-test/modules/mod-users-keycloak/sidecar.yaml
      - $values/folio-test/common/probes.yaml
      - $values/folio-test/modules/mod-users-keycloak/extra_env.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 0.0.51
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
