apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgr-tenants
  namespace: folio-dev
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mgr-tenants
    helm:
      valueFiles:
      - $values/folio-dev/modules/mgr-tenants/mgr-tenants.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 0.0.16
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
