apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-data-import
  namespace: folio-dev
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-data-import
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-data-import/overrides.yaml
      - $values/folio-dev/modules/mod-data-import/resources.yaml
      - $values/common/sidecar.yaml
      - $values/common/probes.yaml
      - $values/folio-dev/modules/mod-data-import/java_opts.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 3.1.44
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
