apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-inventory-update
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-inventory-update
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-inventory-update/overrides.yaml
      - $values/folio-test/common/resources.yaml
      - $values/folio-test/common/sidecar.yaml
      - $values/folio-test/modules/mod-inventory-update/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 3.2.50
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
