image:
  repository: folioorg/mgr-applications
  tag: 2.1.0

deploymentStrategy: RollingUpdate

eureka:
  enabled: true

integrations:
  db:
    enabled: true
    existingSecret: "db-credentials"
  kafka:
    enabled: true
    existingSecret: "kafka-credentials"

extraJavaOpts:
  - "-Dlogging.level.root=DEBUG"

resources:
  limits:
    cpu: 600m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 512Mi

# service:
#   type: ClusterIP
#   ports:
#     - name: http
#       protocol: TCP
#       port: 8081
#       containerPort: 8081
#       targetPort: http

extraEnvVars:
  - name: KC_JWKS_BASE_URL
    value: "http://keycloak:8080"
  - name: MODULE_URL
    value: "http://mgr-applications"
  - name: ROUTEMANAGEMENT_ENABLE
    value: "true"
  - name: kong.url
    valueFrom:
      secretKeyRef:
        name: kong-credentials
        key: KONG_URL
  - name: SECRET_STORE_VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: folio-vault
        key: SECRET_STORE_VAULT_TOKEN
  - name: SECRET_STORE_VAULT_ADDRESS
    valueFrom:
      secretKeyRef:
        name: folio-vault
        key: SECRET_STORE_VAULT_ADDRESS
  - name: SECRET_STORE_VAULT_ENABLE_SSL
    valueFrom:
      secretKeyRef:
        name: folio-vault
        key: SECRET_STORE_VAULT_ENABLE_SSL
