apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-sip2
  namespace: folio-dev
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: edge-sip2
    helm:
      valueFiles:
      - $values/folio-dev/modules/edge-sip2/overrides.yaml
      - $values/folio-dev/modules/edge-sip2/resources.yaml
      - $values/common/sidecar.yaml
      - $values/folio-dev/modules/edge-sip2/probes.yaml
      - $values/folio-dev/modules/edge-sip2/service.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 3.1.50
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
