apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-sip2
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: edge-sip2
    helm:
      valueFiles:
      - $values/folio-test/modules/edge-sip2/overrides.yaml
      - $values/folio-test/common/resources.yaml
      - $values/folio-test/common/sidecar.yaml
      - $values/folio-test/common/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 3.1.50
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
