apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: folio-test
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com/
      targetRevision: 0.32.0
      helm:
        valueFiles:
          - $values/folio-test/infrastructure/vault.yaml
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: fix-vault
      ref: values
  project: folio-test
