apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-serials-management
  namespace: folio-dev
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-serials-management
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-serials-management/overrides.yaml
      - $values/folio-dev/modules/mod-serials-management/resources.yaml
      - $values/common/sidecar.yaml
      - $values/folio-dev/modules/mod-serials-management/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 1.0.48
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
