apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-roles-keycloak
  namespace: folio-dev
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-roles-keycloak
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-roles-keycloak/overrides.yaml
      - $values/folio-dev/modules/mod-roles-keycloak/resources.yaml
      - $values/folio-dev/modules/mod-roles-keycloak/sidecar.yaml
      - $values/common/probes.yaml
      - $values/folio-dev/modules/mod-roles-keycloak/extra_env.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 0.0.51
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
