apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-finance
  namespace: folio-test
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-finance
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-finance/overrides.yaml
      - $values/folio-test/modules/mod-finance/resources.yaml
      - $values/common/sidecar.yaml
      - $values/common/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 4.8.48
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
