apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-inventory
  namespace: folio-dev
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-inventory
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-inventory/overrides.yaml
      - $values/folio-dev/modules/mod-inventory/resources.yaml
      - $values/common/sidecar.yaml
      - $values/folio-dev/modules/mod-inventory/probes.yaml
      - $values/folio-dev/modules/mod-inventory/java_opts.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2/
    targetRevision: 20.2.43
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: argo-cd
